apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata: # kpt-merge: default/nephio-example-packages
  name: nephio-example-packages
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
  annotations:
    internal.kpt.dev/upstream-identifier: 'config.porch.kpt.dev|Repository|default|nephio-example-packages'
spec:
  content: Package
  deployment: false
  git:
    branch: v3.0.0
    directory: /
    repo: https://github.com/nephio-project/nephio-example-packages.git
  type: git
